/*                                                                            */
/* This file is copyright Solid ICE Technologies, Inc., all rights reserved.  */
/* Refer to the license file common/solidicelicense.txt for more details      */
/*                                                                            */

/*
  crc32tab.h
  Generated CRC-32 table - intnded to be included as sub-table

  programmer  generated by makecrc
  date        august 31, 1996
*/
#ifndef CRC32TAB_H
#define CRC32TAB_H

#include <stdint.h>

namespace go {

extern  uint32_t crc_32_tab[] ;

} // namespace go 

#endif

